openapi: 3.0.3
info:
  title: Football Competition Management API
  description: API for managing football competitions, teams, and players.
  version: 1.0.0
servers:
  - url: https://api-football.com/rnt
paths:
